import { apiDelete, apiGet, apiPost } from "./lib/api";
import "./index.css";

type ScanType = "url" | "screenshot" | "text";
type Severity = "Low" | "Medium" | "High";

interface PatternDetail { category: string; severity: Severity; evidence: string; recommendation: string }
interface ScanRecord { id: string; target_url: string | null; scan_type: ScanType; severity: Severity; risk_score: number; patterns_found: number; pattern_details: PatternDetail[]; notes: string | null; created_at: string }
interface Stats { total_scans: number; high_risk_sites: number; most_common_pattern: string; total_reports: number; last_scan_at: string | null }
interface ContactReport { id: string; status: string; created_at: string }

const app = document.querySelector<HTMLDivElement>("#app");
if (!app) throw new Error("DarkShield root not found");
const root = app;

let scanType: ScanType = "url";
let scans: ScanRecord[] = [];
let latestScan: ScanRecord | null = null;
let quizIndex = 0;
let quizScore = 0;
let quizAnswer: number | null = null;
let quizFinished = false;

const quizQuestions = [
  { prompt: "A checkout timer resets every time you refresh. What should you suspect?", options: ["A real warehouse deadline", "Fake urgency", "A secure payment step", "A delivery estimate"], answer: 1 },
  { prompt: "Which is a healthy alternative to a pre-selected add-on?", options: ["A clear opt-in checkbox", "A hidden fee", "A forced signup", "A guilt-filled decline button"], answer: 0 },
  { prompt: "What is drip pricing?", options: ["A loyalty reward", "A discount that grows", "Costs revealed late in checkout", "A product comparison"], answer: 2 },
];

const presets = [
  ["Amazon India", "https://amazon.in", "preset-amazon-btn"],
  ["Flipkart", "https://flipkart.com", "preset-flipkart-btn"],
  ["Myntra", "https://myntra.com", "preset-myntra-btn"],
  ["Meesho", "https://meesho.com", "preset-meesho-btn"],
];

function escapeHtml(value: string) {
  return value.replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character] ?? character);
}

function formatDate(value: string) { return new Date(value).toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" }); }
function severityClass(severity: Severity) { return `risk-${severity.toLowerCase()}`; }
function toast(message: string, kind: "success" | "error" = "success") {
  const node = document.createElement("div");
  node.className = `toast toast-${kind}`;
  node.textContent = message;
  node.setAttribute("data-testid", "toast-message");
  document.body.append(node);
  window.setTimeout(() => node.remove(), 3200);
}

function shell() {
  root.innerHTML = `
    <header class="site-header" data-testid="site-header"><div class="shell header-inner">
      <a class="brand" data-testid="nav-brand-logo" href="#top"><span class="brand-mark">✦</span><span><strong>DarkShield</strong><small>MCA / REGEX ENGINE</small></span></a>
      <nav class="desktop-nav" data-testid="desktop-navigation"><a data-testid="nav-scanner-link" href="#scanner">Live scanner</a><a data-testid="nav-records-link" href="#records">Records</a><a data-testid="nav-quiz-link" href="#quiz">Quiz</a><a data-testid="nav-contact-link" href="#contact">Report a trap</a></nav>
      <span class="system-pill" data-testid="nav-status-pill"><i></i> system ready</span><a data-testid="nav-scan-cta" class="button button-primary header-cta" href="#scanner">Analyze store →</a>
    </div></header>
    <main id="top" class="shell page-main">
      <section class="hero" data-testid="hero-section"><div class="hero-copy"><p class="eyebrow" data-testid="hero-eyebrow"><i></i> DIGITAL CONSUMER DEFENSE</p><h1 data-testid="hero-title">See what the page <em>isn't telling you.</em></h1><p class="hero-description" data-testid="hero-description">DarkShield reveals the pressure tactics hidden in e-commerce copy, so you can slow down, compare the evidence, and choose with confidence.</p><div class="hero-stats" data-testid="hero-stat-row"><span data-testid="hero-stat-patterns"><b>06</b> pattern classes</span><span data-testid="hero-stat-mode"><b>03</b> audit modes</span><span data-testid="hero-stat-storage"><b>100%</b> local rules</span></div></div><div class="radar-card" data-testid="hero-radar-card"><div class="grid-glow"></div><div class="radar-top"><span data-testid="hero-radar-label">SIGNAL MONITOR / 01</span><span data-testid="hero-radar-live" class="live-label"><i></i> live</span></div><div class="radar"><span class="radar-ring ring-one"></span><span class="radar-ring ring-two"></span><span class="radar-cross"></span><span class="radar-core">✦</span></div><div class="radar-metrics"><div data-testid="hero-radar-metric-one"><b id="stat-scans">0</b><small>audits run</small></div><div data-testid="hero-radar-metric-two"><b id="stat-high">0</b><small>high risk</small></div><div data-testid="hero-radar-metric-three"><b>6</b><small>rule families</small></div></div></div></section>
      <section id="scanner" class="section scroll-target" data-testid="scanner-section"><div class="section-heading"><div><p class="eyebrow" data-testid="scanner-eyebrow">01 / LIVE SCANNER</p><h2 data-testid="scanner-title">Interrogate the checkout copy.</h2></div><p data-testid="scanner-helper">Run a quick rule-based audit. For a deeper read, paste visible page text into raw text mode.</p></div><div class="scanner-card" data-testid="scanner-card"><div class="mode-tabs"><button class="mode-tab active" data-testid="tab-url-mode" data-mode="url">⌕ URL analysis</button><button class="mode-tab" data-testid="tab-screenshot-mode" data-mode="screenshot">▣ Screenshot OCR</button><button class="mode-tab" data-testid="tab-rawtext-mode" data-mode="text">▤ Raw text paste</button></div><form id="scanner-form" data-testid="scanner-form"><label id="scanner-label" data-testid="scanner-input-label" for="scanner-input">STORE URL</label><div class="scanner-row"><input id="scanner-input" data-testid="hero-url-input" type="url" placeholder="https://your-store.com" required><button data-testid="hero-scan-submit-btn" class="button button-primary" type="submit">Analyze now <span>→</span></button></div><div id="screenshot-options" class="upload-row hidden"><span><b>Upload a screenshot</b> <small>(optional)</small><em>Paste its visible text above for local OCR simulation.</em></span><label class="file-button" data-testid="screenshot-upload-label">▣ Choose JPG / PNG<input data-testid="screenshot-file-input" type="file" accept="image/png,image/jpeg"></label></div></form><div class="preset-wrap"><p data-testid="preset-label">✧ QUICK AUDIT PRESETS</p><div class="preset-list">${presets.map(([label, url, id]) => `<button data-testid="${id}" class="preset button button-outline" data-url="${url}"><i></i>${label}</button>`).join("")}</div></div></div></section>
      <section id="results" class="section scroll-target" data-testid="results-section"><div class="section-heading"><div><p class="eyebrow" data-testid="results-eyebrow">02 / INTELLIGENCE</p><h2 data-testid="results-section-title">Your evidence, decoded.</h2></div><span class="linked-status" data-testid="results-query-state"><i></i> MONGO HISTORY LINKED</span></div><div id="results-content"></div></section>
      <section id="records" class="section scroll-target" data-testid="records-section"><div class="section-heading"><div><p class="eyebrow" data-testid="records-eyebrow">03 / AUDIT RECORDS</p><h2 data-testid="records-title">Keep your receipts.</h2></div><p data-testid="records-helper">Every scan is saved in MongoDB so you can compare pressure tactics over time.</p></div><div class="records-card" data-testid="records-table"><div class="record-controls"><input id="records-search" data-testid="records-search-input" placeholder="⌕  Search stores or patterns"><select id="records-filter" data-testid="records-filter-severity"><option value="all">All risk</option><option value="High">High risk</option><option value="Medium">Medium risk</option><option value="Low">Low risk</option></select></div><div id="records-list"></div></div></section>
      <section id="quiz" class="section quiz-layout scroll-target" data-testid="quiz-section"><div class="quiz-copy"><p class="eyebrow" data-testid="quiz-section-eyebrow">04 / AWARENESS LAB</p><h2 data-testid="quiz-section-title">Build better instincts.</h2><p data-testid="quiz-section-copy">Dark patterns work best when they move fast. Take a 60-second challenge to practice pausing at the right moments.</p><ul data-testid="quiz-benefit-list"><li>✓ Immediate feedback after every answer</li><li>✓ Clear language, no jargon</li><li>✓ A score you can share in your viva</li></ul></div><div class="quiz-card" data-testid="quiz-card"><div class="quiz-top"><p data-testid="quiz-eyebrow">AWARENESS CHALLENGE</p><span id="quiz-progress" data-testid="quiz-progress">1 / 3</span></div><h3 data-testid="quiz-title">Can you spot the trap?</h3><div id="quiz-content"></div></div></section>
      <section id="contact" class="section contact-layout scroll-target" data-testid="contact-section"><div class="contact-copy"><p class="eyebrow" data-testid="contact-eyebrow">05 / INCIDENT REPORT</p><h2 data-testid="contact-title">Found a trap? Leave a trace.</h2><p data-testid="contact-copy">Share the URL and context. Reports are saved for review and help turn one suspicious checkout into a better public signal.</p><div class="assurance" data-testid="contact-assurance">⌾ <span>No account required. This academic demo stores the report in the local DarkShield database.</span></div></div><form id="contact-form" class="contact-card" data-testid="contact-form"><div class="form-grid"><label data-testid="contact-name-label">Your name<input data-testid="contact-name-input" name="full_name" required placeholder="Asha Mehta"></label><label data-testid="contact-email-label">Email address<input data-testid="contact-email-input" name="email" type="email" required placeholder="asha@example.com"></label><label class="full" data-testid="contact-url-label">Store name or URL<input data-testid="contact-url-input" name="store_name" required placeholder="Store or checkout URL"></label><label class="full" data-testid="contact-category-label">What did you notice?<select data-testid="contact-pattern-type-select" name="dark_pattern_category" required><option value="">Select a pattern category</option><option>Fake Urgency</option><option>Hidden Fees</option><option>Confirm Shaming</option><option>Forced Continuity</option><option>Bait & Switch</option><option>Other</option></select></label><label class="full" data-testid="contact-message-label">Evidence notes<textarea data-testid="contact-message-input" name="evidence_notes" required minlength="10" placeholder="What happened, and where did you see it?"></textarea></label></div><div class="form-submit"><span data-testid="contact-form-helper">Your report receives a local tracking id.</span><button data-testid="contact-submit-btn" class="button button-primary" type="submit">Submit report →</button></div><div id="contact-success" class="success-alert hidden" data-testid="contact-success-alert">✓ Report saved. Thank you for leaving a trace.</div></form></section>
    </main><footer class="site-footer" data-testid="site-footer"><div class="shell footer-inner"><div><strong data-testid="footer-credits">✦ DarkShield</strong><small data-testid="footer-description">A local-first dark-pattern awareness project.</small></div><span data-testid="footer-status-pill" class="live-label"><i></i> RULES ENGINE / READY</span><span data-testid="footer-github-link">Built for responsible shopping</span></div></footer>`;
}

function renderResults(scan: ScanRecord | null) {
  const target = document.querySelector<HTMLDivElement>("#results-content");
  if (!target) return;
  if (!scan) { target.innerHTML = `<div class="empty-card" data-testid="results-empty-state"><strong data-testid="results-empty-title">Your first audit is waiting</strong><p data-testid="results-empty-copy">Run a scan above and this panel will unpack the copy that deserves a second look.</p></div>`; return; }
  const meterColor = scan.severity === "High" ? "#fb7185" : scan.severity === "Medium" ? "#fbbf24" : "#34d399";
  target.innerHTML = `<div class="results-card" data-testid="results-dashboard"><div class="results-head"><div><span class="result-kicker" data-testid="results-live-badge">LATEST AUDIT</span><span class="result-meta" data-testid="results-scan-type">${escapeHtml(scan.scan_type)} analysis / ${formatDate(scan.created_at)}</span><h3 data-testid="results-heading">Risk signals detected.</h3><p data-testid="results-target">${escapeHtml(scan.target_url || "Pasted page content")}</p></div><button data-testid="results-export-pdf-btn" id="print-report" class="button button-outline">▣ Export report</button></div><div class="results-grid"><div class="meter-wrap" data-testid="results-risk-meter"><div class="meter" style="--meter:${scan.risk_score}%;--meter-color:${meterColor}"><div><b data-testid="results-risk-score">${scan.risk_score}</b><small>RISK INDEX</small></div></div><span class="risk-badge ${severityClass(scan.severity)}" data-testid="results-severity-badge">${scan.severity} risk</span><small data-testid="results-patterns-count">${scan.patterns_found} pattern${scan.patterns_found === 1 ? "" : "s"} matched</small></div><div class="pattern-column"><div class="pattern-heading"><span><b data-testid="results-patterns-label">SIGNAL BREAKDOWN</b><small data-testid="results-patterns-helper">Evidence captured by the local regex engine.</small></span><span class="live-label" data-testid="results-engine-status"><i></i> ENGINE ONLINE</span></div>${scan.pattern_details.length ? scan.pattern_details.map((pattern) => `<article class="pattern-item" data-testid="results-pattern-item"><div><strong data-testid="results-pattern-category">✧ ${escapeHtml(pattern.category)}</strong><span class="risk-badge ${severityClass(pattern.severity)}">${pattern.severity}</span></div><p data-testid="results-pattern-evidence">“${escapeHtml(pattern.evidence)}”</p><small data-testid="results-pattern-recommendation">${escapeHtml(pattern.recommendation)}</small></article>`).join("") : `<div class="no-patterns" data-testid="results-no-patterns">No known dark-pattern phrases matched this sample. Keep checking the final total before completing checkout.</div>`}</div></div></div>`;
  document.querySelector<HTMLButtonElement>("#print-report")?.addEventListener("click", () => { window.print(); toast("Print-ready audit report opened"); });
}

function renderRecords() {
  const list = document.querySelector<HTMLDivElement>("#records-list");
  const search = document.querySelector<HTMLInputElement>("#records-search")?.value.toLowerCase() ?? "";
  const filter = document.querySelector<HTMLSelectElement>("#records-filter")?.value ?? "all";
  if (!list) return;
  const filtered = scans.filter((scan) => `${scan.target_url ?? ""} ${scan.pattern_details.map((pattern) => pattern.category).join(" ")}`.toLowerCase().includes(search) && (filter === "all" || scan.severity === filter));
  if (!filtered.length) { list.innerHTML = `<div class="empty-card compact" data-testid="records-empty-state"><strong data-testid="records-empty-title">No audit records yet</strong><p data-testid="records-empty-copy">Your next scan will appear here.</p></div>`; return; }
  list.innerHTML = filtered.map((scan) => `<article class="record-row" data-testid="records-row"><div class="record-main"><strong data-testid="records-row-url">${escapeHtml(scan.target_url || "Pasted page content")}</strong><span class="risk-badge ${severityClass(scan.severity)}">${scan.severity} risk</span><small data-testid="records-row-meta">${formatDate(scan.created_at)} · ${scan.patterns_found} signals · ${scan.risk_score} index</small></div><div class="record-actions"><button data-testid="records-inspect-btn" class="button button-outline inspect" data-id="${scan.id}">Inspect ›</button><button data-testid="records-delete-btn" class="icon-button delete" data-id="${scan.id}" aria-label="Delete record">×</button></div><div class="inspection hidden" id="inspect-${scan.id}" data-testid="records-inspection-panel">${scan.pattern_details.length ? scan.pattern_details.map((pattern) => `<span data-testid="records-inspection-item"><b>${escapeHtml(pattern.category)}</b><small>${escapeHtml(pattern.evidence)}</small></span>`).join("") : `<small data-testid="records-inspection-empty">No pattern evidence was matched.</small>`}</div></article>`).join("");
  list.querySelectorAll<HTMLButtonElement>(".inspect").forEach((button) => button.addEventListener("click", () => document.querySelector(`#inspect-${button.dataset.id}`)?.classList.toggle("hidden")));
  list.querySelectorAll<HTMLButtonElement>(".delete").forEach((button) => button.addEventListener("click", () => { const id = button.dataset.id; if (!id) return; void apiDelete<void>(`/scans/${id}`).then(() => { scans = scans.filter((scan) => scan.id !== id); if (latestScan?.id === id) { latestScan = scans[0] ?? null; renderResults(latestScan); } renderRecords(); updateStats(); toast("Audit record deleted"); }).catch(() => toast("That record could not be deleted", "error")); }));
}

function updateStats() { const scansNode = document.querySelector("#stat-scans"); const highNode = document.querySelector("#stat-high"); if (scansNode) scansNode.textContent = String(scans.length); if (highNode) highNode.textContent = String(scans.filter((scan) => scan.severity === "High").length); }
async function loadData() { try { scans = await apiGet<ScanRecord[]>("/scans"); latestScan = scans[0] ?? null; renderResults(latestScan); renderRecords(); updateStats(); } catch { renderResults(null); renderRecords(); } try { const stats = await apiGet<Stats>("/stats"); document.querySelector("#stat-scans")!.textContent = String(stats.total_scans); document.querySelector("#stat-high")!.textContent = String(stats.high_risk_sites); } catch { /* static shell remains useful when the API is paused */ } }

function renderQuiz() {
  const target = document.querySelector<HTMLDivElement>("#quiz-content"); const progress = document.querySelector("#quiz-progress"); if (!target || !progress) return;
  if (quizFinished) { progress.textContent = "COMPLETE"; target.innerHTML = `<div class="quiz-result" data-testid="quiz-score-badge"><b data-testid="quiz-score-title">${quizScore}/${quizQuestions.length} correct</b><p data-testid="quiz-score-copy">${quizScore === quizQuestions.length ? "Sharp eyes. You’re ready to audit your next checkout." : "You’re building the right instincts. A second look is always worth it."}</p><button id="quiz-restart" data-testid="quiz-restart-btn" class="button button-outline">Try again</button></div>`; document.querySelector("#quiz-restart")?.addEventListener("click", () => { quizIndex = 0; quizScore = 0; quizAnswer = null; quizFinished = false; renderQuiz(); }); return; }
  const question = quizQuestions[quizIndex]; progress.textContent = `${quizIndex + 1} / ${quizQuestions.length}`; target.innerHTML = `<p class="quiz-question" data-testid="quiz-question">${question.prompt}</p><div class="quiz-options">${question.options.map((option, index) => `<button data-testid="quiz-option-btn" class="quiz-option ${quizAnswer === index ? "selected" : ""} ${quizAnswer !== null && index === question.answer ? "correct" : ""}" data-answer="${index}">${String.fromCharCode(65 + index)} <span>${option}</span></button>`).join("")}</div><div class="quiz-footer"><small data-testid="quiz-hint">Choose an answer to continue</small><button id="quiz-next" data-testid="quiz-next-btn" class="button button-primary" ${quizAnswer === null ? "disabled" : ""}>${quizIndex === quizQuestions.length - 1 ? "See score" : "Next question"} →</button></div>`;
  target.querySelectorAll<HTMLButtonElement>(".quiz-option").forEach((button) => button.addEventListener("click", () => { if (quizAnswer === null) { quizAnswer = Number(button.dataset.answer); renderQuiz(); } }));
  target.querySelector("#quiz-next")?.addEventListener("click", () => { if (quizAnswer === null) return; quizScore += quizAnswer === question.answer ? 1 : 0; if (quizIndex === quizQuestions.length - 1) quizFinished = true; else { quizIndex += 1; quizAnswer = null; } renderQuiz(); });
}

function wireEvents() {
  document.querySelectorAll<HTMLButtonElement>("[data-mode]").forEach((button) => button.addEventListener("click", () => { scanType = button.dataset.mode as ScanType; document.querySelectorAll("[data-mode]").forEach((tab) => tab.classList.toggle("active", tab === button)); const input = document.querySelector<HTMLInputElement | HTMLTextAreaElement>("#scanner-input"); const label = document.querySelector("#scanner-label"); const upload = document.querySelector("#screenshot-options"); if (scanType === "url") { input?.setAttribute("type", "url"); input?.setAttribute("placeholder", "https://your-store.com"); input?.setAttribute("required", "true"); if (label) label.textContent = "STORE URL"; upload?.classList.add("hidden"); } else { input?.setAttribute("type", "text"); input?.removeAttribute("required"); input?.setAttribute("placeholder", "Paste the product or checkout text you want to inspect…"); if (label) label.textContent = "VISIBLE COPY"; upload?.classList.toggle("hidden", scanType !== "screenshot"); } }));
  document.querySelectorAll<HTMLButtonElement>("[data-url]").forEach((button) => button.addEventListener("click", () => { scanType = "url"; const input = document.querySelector<HTMLInputElement>("#scanner-input"); if (input) input.value = button.dataset.url ?? ""; document.querySelector("#scanner")?.scrollIntoView({ behavior: "smooth" }); }));
  document.querySelector<HTMLFormElement>("#scanner-form")?.addEventListener("submit", (event) => { event.preventDefault(); const input = document.querySelector<HTMLInputElement>("#scanner-input"); const value = input?.value.trim() ?? ""; if (!value && scanType === "url") { toast("Add a store URL first", "error"); return; } if (!value && scanType === "text") { toast("Paste page text first", "error"); return; } const submit = document.querySelector<HTMLButtonElement>("[data-testid=hero-scan-submit-btn]"); if (submit) { submit.disabled = true; submit.textContent = "Analyzing…"; } void apiPost<ScanRecord>("/scans", { scan_type: scanType, target_url: scanType === "url" ? value : undefined, raw_text: scanType === "url" ? undefined : value || "Screenshot uploaded for visual review." }).then((scan) => { latestScan = scan; scans = [scan, ...scans]; renderResults(scan); renderRecords(); updateStats(); toast("Audit complete — signals mapped"); document.querySelector("#results")?.scrollIntoView({ behavior: "smooth" }); }).catch(() => toast("Audit could not run. Check the input and try again.", "error")).finally(() => { if (submit) { submit.disabled = false; submit.innerHTML = "Analyze now <span>→</span>"; } }); });
  document.querySelector<HTMLInputElement>("#records-search")?.addEventListener("input", renderRecords); document.querySelector<HTMLSelectElement>("#records-filter")?.addEventListener("change", renderRecords);
  document.querySelector<HTMLInputElement>("[data-testid=screenshot-file-input]")?.addEventListener("change", (event) => { const input = event.target as HTMLInputElement; const label = document.querySelector("[data-testid=screenshot-upload-label]"); if (label && input.files?.[0]) label.childNodes[0].textContent = `▣ ${input.files[0].name}`; });
  document.querySelector<HTMLFormElement>("#contact-form")?.addEventListener("submit", (event) => { event.preventDefault(); const form = event.currentTarget as HTMLFormElement; const data = new FormData(form); const payload = Object.fromEntries(data.entries()) as Record<string, string>; const submit = document.querySelector<HTMLButtonElement>("[data-testid=contact-submit-btn]"); if (submit) { submit.disabled = true; submit.textContent = "Saving report…"; } void apiPost<ContactReport>("/contacts", payload).then(() => { form.reset(); document.querySelector("#contact-success")?.classList.remove("hidden"); toast("Report received"); }).catch(() => toast("Please check the report details and try again", "error")).finally(() => { if (submit) { submit.disabled = false; submit.textContent = "Submit report →"; } }); });
}

shell(); wireEvents(); renderQuiz(); void loadData();